import { db } from '@/db';
import { albums } from '@/db/schema';

async function main() {
    const sampleAlbums = [
        // Artist 1 albums
        {
            artistId: 1,
            title: 'Midnight Dreams',
            releaseDate: new Date('2024-03-15'),
            coverUrl: 'https://picsum.photos/400x400?random=1',
            popularity: 85,
            createdAt: new Date('2024-03-15'),
        },
        {
            artistId: 1,
            title: 'Greatest Hits Collection',
            releaseDate: new Date('2023-11-20'),
            coverUrl: 'https://picsum.photos/400x400?random=2',
            popularity: 92,
            createdAt: new Date('2023-11-20'),
        },
        // Artist 2 albums
        {
            artistId: 2,
            title: 'Electric Nights',
            releaseDate: new Date('2024-01-10'),
            coverUrl: 'https://picsum.photos/400x400?random=3',
            popularity: 78,
            createdAt: new Date('2024-01-10'),
        },
        {
            artistId: 2,
            title: 'Synthwave EP',
            releaseDate: new Date('2023-08-05'),
            coverUrl: null,
            popularity: 65,
            createdAt: new Date('2023-08-05'),
        },
        {
            artistId: 2,
            title: 'Live at Electric Festival',
            releaseDate: new Date('2023-06-12'),
            coverUrl: 'https://picsum.photos/400x400?random=4',
            popularity: 71,
            createdAt: new Date('2023-06-12'),
        },
        // Artist 3 albums
        {
            artistId: 3,
            title: 'Acoustic Sessions',
            releaseDate: new Date('2024-02-28'),
            coverUrl: 'https://picsum.photos/400x400?random=5',
            popularity: 89,
            createdAt: new Date('2024-02-28'),
        },
        // Artist 4 albums
        {
            artistId: 4,
            title: 'Bass Drop Chronicles',
            releaseDate: new Date('2024-01-22'),
            coverUrl: 'https://picsum.photos/400x400?random=6',
            popularity: 82,
            createdAt: new Date('2024-01-22'),
        },
        {
            artistId: 4,
            title: 'Underground Anthems',
            releaseDate: new Date('2023-09-15'),
            coverUrl: null,
            popularity: 74,
            createdAt: new Date('2023-09-15'),
        },
        {
            artistId: 4,
            title: 'Remixed & Remastered',
            releaseDate: new Date('2022-12-08'),
            coverUrl: 'https://picsum.photos/400x400?random=7',
            popularity: 67,
            createdAt: new Date('2022-12-08'),
        },
        // Artist 5 albums
        {
            artistId: 5,
            title: 'Country Roads',
            releaseDate: new Date('2023-10-30'),
            coverUrl: 'https://picsum.photos/400x400?random=8',
            popularity: 76,
            createdAt: new Date('2023-10-30'),
        },
        {
            artistId: 5,
            title: 'Hometown Stories',
            releaseDate: new Date('2022-05-18'),
            coverUrl: 'https://picsum.photos/400x400?random=9',
            popularity: 69,
            createdAt: new Date('2022-05-18'),
        },
        // Artist 6 albums
        {
            artistId: 6,
            title: 'Jazz After Dark',
            releaseDate: new Date('2024-04-02'),
            coverUrl: 'https://picsum.photos/400x400?random=10',
            popularity: 88,
            createdAt: new Date('2024-04-02'),
        },
        // Artist 7 albums
        {
            artistId: 7,
            title: 'Heavy Metal Thunder',
            releaseDate: new Date('2023-12-11'),
            coverUrl: 'https://picsum.photos/400x400?random=11',
            popularity: 91,
            createdAt: new Date('2023-12-11'),
        },
        {
            artistId: 7,
            title: 'Apocalypse Now',
            releaseDate: new Date('2022-07-22'),
            coverUrl: null,
            popularity: 83,
            createdAt: new Date('2022-07-22'),
        },
        // Artist 8 albums
        {
            artistId: 8,
            title: 'Urban Legends',
            releaseDate: new Date('2024-01-08'),
            coverUrl: 'https://picsum.photos/400x400?random=12',
            popularity: 79,
            createdAt: new Date('2024-01-08'),
        },
        {
            artistId: 8,
            title: 'Street Chronicles EP',
            releaseDate: new Date('2023-07-14'),
            coverUrl: 'https://picsum.photos/400x400?random=13',
            popularity: 72,
            createdAt: new Date('2023-07-14'),
        },
        {
            artistId: 8,
            title: 'Live from the Block',
            releaseDate: new Date('2023-03-25'),
            coverUrl: null,
            popularity: 68,
            createdAt: new Date('2023-03-25'),
        },
        // Artist 9 albums
        {
            artistId: 9,
            title: 'Indie Vibes',
            releaseDate: new Date('2023-11-05'),
            coverUrl: 'https://picsum.photos/400x400?random=14',
            popularity: 75,
            createdAt: new Date('2023-11-05'),
        },
        // Artist 10 albums
        {
            artistId: 10,
            title: 'Classical Masterpieces',
            releaseDate: new Date('2024-02-14'),
            coverUrl: 'https://picsum.photos/400x400?random=15',
            popularity: 86,
            createdAt: new Date('2024-02-14'),
        },
        {
            artistId: 10,
            title: 'Symphony No. 5 Live',
            releaseDate: new Date('2022-10-12'),
            coverUrl: 'https://picsum.photos/400x400?random=16',
            popularity: 81,
            createdAt: new Date('2022-10-12'),
        },
        // Artist 11 albums
        {
            artistId: 11,
            title: 'Punk Revolution',
            releaseDate: new Date('2023-09-28'),
            coverUrl: null,
            popularity: 73,
            createdAt: new Date('2023-09-28'),
        },
        {
            artistId: 11,
            title: 'Anarchy Rules',
            releaseDate: new Date('2022-04-07'),
            coverUrl: 'https://picsum.photos/400x400?random=17',
            popularity: 66,
            createdAt: new Date('2022-04-07'),
        },
        // Artist 12 albums
        {
            artistId: 12,
            title: 'Reggae Sunrise',
            releaseDate: new Date('2024-03-20'),
            coverUrl: 'https://picsum.photos/400x400?random=18',
            popularity: 84,
            createdAt: new Date('2024-03-20'),
        },
        // Artist 13 albums
        {
            artistId: 13,
            title: 'Folk Tales',
            releaseDate: new Date('2023-08-18'),
            coverUrl: 'https://picsum.photos/400x400?random=19',
            popularity: 77,
            createdAt: new Date('2023-08-18'),
        },
        {
            artistId: 13,
            title: 'Campfire Songs',
            releaseDate: new Date('2022-06-30'),
            coverUrl: null,
            popularity: 70,
            createdAt: new Date('2022-06-30'),
        },
        // Artist 14 albums
        {
            artistId: 14,
            title: 'Blues Highway',
            releaseDate: new Date('2024-01-15'),
            coverUrl: 'https://picsum.photos/400x400?random=20',
            popularity: 80,
            createdAt: new Date('2024-01-15'),
        },
        {
            artistId: 14,
            title: 'Delta Soul',
            releaseDate: new Date('2022-11-22'),
            coverUrl: 'https://picsum.photos/400x400?random=21',
            popularity: 74,
            createdAt: new Date('2022-11-22'),
        },
        {
            artistId: 14,
            title: 'Live at Blues Club',
            releaseDate: new Date('2021-09-03'),
            coverUrl: 'https://picsum.photos/400x400?random=22',
            popularity: 62,
            createdAt: new Date('2021-09-03'),
        },
        // Artist 15 albums
        {
            artistId: 15,
            title: 'Funk Masters',
            releaseDate: new Date('2023-12-05'),
            coverUrl: 'https://picsum.photos/400x400?random=23',
            popularity: 78,
            createdAt: new Date('2023-12-05'),
        },
        // Artist 16 albums
        {
            artistId: 16,
            title: 'Gospel Glory',
            releaseDate: new Date('2024-04-07'),
            coverUrl: 'https://picsum.photos/400x400?random=24',
            popularity: 87,
            createdAt: new Date('2024-04-07'),
        },
        {
            artistId: 16,
            title: 'Praise & Worship',
            releaseDate: new Date('2023-01-12'),
            coverUrl: null,
            popularity: 76,
            createdAt: new Date('2023-01-12'),
        },
        // Artist 17 albums
        {
            artistId: 17,
            title: 'World Fusion',
            releaseDate: new Date('2023-10-08'),
            coverUrl: 'https://picsum.photos/400x400?random=25',
            popularity: 71,
            createdAt: new Date('2023-10-08'),
        },
        // Artist 18 albums
        {
            artistId: 18,
            title: 'Alternative Universe',
            releaseDate: new Date('2024-02-22'),
            coverUrl: 'https://picsum.photos/400x400?random=26',
            popularity: 83,
            createdAt: new Date('2024-02-22'),
        },
        {
            artistId: 18,
            title: 'Experimental Sounds',
            releaseDate: new Date('2022-08-14'),
            coverUrl: 'https://picsum.photos/400x400?random=27',
            popularity: 67,
            createdAt: new Date('2022-08-14'),
        },
        // Artist 19 albums
        {
            artistId: 19,
            title: 'Ambient Dreams',
            releaseDate: new Date('2023-11-15'),
            coverUrl: null,
            popularity: 72,
            createdAt: new Date('2023-11-15'),
        },
        {
            artistId: 19,
            title: 'Soundscapes',
            releaseDate: new Date('2022-03-28'),
            coverUrl: 'https://picsum.photos/400x400?random=28',
            popularity: 65,
            createdAt: new Date('2022-03-28'),
        },
        // Artist 20 albums
        {
            artistId: 20,
            title: 'Latin Fire',
            releaseDate: new Date('2024-03-08'),
            coverUrl: 'https://picsum.photos/400x400?random=29',
            popularity: 89,
            createdAt: new Date('2024-03-08'),
        },
        // Artist 21 albums
        {
            artistId: 21,
            title: 'Celtic Winds',
            releaseDate: new Date('2023-07-25'),
            coverUrl: 'https://picsum.photos/400x400?random=30',
            popularity: 74,
            createdAt: new Date('2023-07-25'),
        },
        // Artist 22 albums
        {
            artistId: 22,
            title: 'Smooth Jazz Nights',
            releaseDate: new Date('2024-01-30'),
            coverUrl: 'https://picsum.photos/400x400?random=31',
            popularity: 81,
            createdAt: new Date('2024-01-30'),
        },
        {
            artistId: 22,
            title: 'Lounge Sessions',
            releaseDate: new Date('2022-12-16'),
            coverUrl: null,
            popularity: 73,
            createdAt: new Date('2022-12-16'),
        },
        // Artist 23 albums
        {
            artistId: 23,
            title: 'Progressive Rock Saga',
            releaseDate: new Date('2023-09-12'),
            coverUrl: 'https://picsum.photos/400x400?random=32',
            popularity: 76,
            createdAt: new Date('2023-09-12'),
        },
        {
            artistId: 23,
            title: 'Concept Album',
            releaseDate: new Date('2021-11-04'),
            coverUrl: 'https://picsum.photos/400x400?random=33',
            popularity: 68,
            createdAt: new Date('2021-11-04'),
        },
        // Artist 24 albums
        {
            artistId: 24,
            title: 'Grunge Revival',
            releaseDate: new Date('2024-02-05'),
            coverUrl: 'https://picsum.photos/400x400?random=34',
            popularity: 82,
            createdAt: new Date('2024-02-05'),
        },
        // Artist 25 albums
        {
            artistId: 25,
            title: 'Trap Beats Volume 1',
            releaseDate: new Date('2024-04-12'),
            coverUrl: 'https://picsum.photos/400x400?random=35',
            popularity: 95,
            createdAt: new Date('2024-04-12'),
        },
        {
            artistId: 25,
            title: 'Mixtape Madness',
            releaseDate: new Date('2023-10-20'),
            coverUrl: null,
            popularity: 88,
            createdAt: new Date('2023-10-20'),
        },
        {
            artistId: 25,
            title: 'Hood Chronicles',
            releaseDate: new Date('2023-05-17'),
            coverUrl: 'https://picsum.photos/400x400?random=36',
            popularity: 79,
            createdAt: new Date('2023-05-17'),
        },
        // Artist 26 albums
        {
            artistId: 26,
            title: 'Emo Confessions',
            releaseDate: new Date('2023-08-30'),
            coverUrl: 'https://picsum.photos/400x400?random=37',
            popularity: 75,
            createdAt: new Date('2023-08-30'),
        },
        // Artist 27 albums
        {
            artistId: 27,
            title: 'Ska Madness',
            releaseDate: new Date('2024-01-18'),
            coverUrl: 'https://picsum.photos/400x400?random=38',
            popularity: 77,
            createdAt: new Date('2024-01-18'),
        },
        {
            artistId: 27,
            title: 'Two Tone Revival',
            releaseDate: new Date('2022-09-08'),
            coverUrl: 'https://picsum.photos/400x400?random=39',
            popularity: 69,
            createdAt: new Date('2022-09-08'),
        },
        // Artist 28 albums
        {
            artistId: 28,
            title: 'Garage Rock Revival',
            releaseDate: new Date('2023-06-22'),
            coverUrl: null,
            popularity: 70,
            createdAt: new Date('2023-06-22'),
        },
        // Artist 29 albums
        {
            artistId: 29,
            title: 'Psychedelic Journey',
            releaseDate: new Date('2024-03-25'),
            coverUrl: 'https://picsum.photos/400x400?random=40',
            popularity: 84,
            createdAt: new Date('2024-03-25'),
        },
        {
            artistId: 29,
            title: 'Mind Expansion EP',
            releaseDate: new Date('2023-01-28'),
            coverUrl: 'https://picsum.photos/400x400?random=41',
            popularity: 71,
            createdAt: new Date('2023-01-28'),
        },
        // Artist 30 albums
        {
            artistId: 30,
            title: 'New Wave Nostalgia',
            releaseDate: new Date('2023-11-30'),
            coverUrl: 'https://picsum.photos/400x400?random=42',
            popularity: 78,
            createdAt: new Date('2023-11-30'),
        },
        // Artist 31 albums
        {
            artistId: 31,
            title: 'Hardcore Punk Anthems',
            releaseDate: new Date('2024-02-10'),
            coverUrl: 'https://picsum.photos/400x400?random=43',
            popularity: 73,
            createdAt: new Date('2024-02-10'),
        },
        // Artist 32 albums
        {
            artistId: 32,
            title: 'Doom Metal Chronicles',
            releaseDate: new Date('2023-07-07'),
            coverUrl: null,
            popularity: 72,
            createdAt: new Date('2023-07-07'),
        },
        {
            artistId: 32,
            title: 'Eternal Darkness',
            releaseDate: new Date('2021-12-15'),
            coverUrl: 'https://picsum.photos/400x400?random=44',
            popularity: 64,
            createdAt: new Date('2021-12-15'),
        },
        // Artist 33 albums
        {
            artistId: 33,
            title: 'Black Metal Abyss',
            releaseDate: new Date('2023-10-13'),
            coverUrl: 'https://picsum.photos/400x400?random=45',
            popularity: 69,
            createdAt: new Date('2023-10-13'),
        },
        // Artist 34 albums
        {
            artistId: 34,
            title: 'Death Metal Massacre',
            releaseDate: new Date('2024-01-25'),
            coverUrl: 'https://picsum.photos/400x400?random=46',
            popularity: 75,
            createdAt: new Date('2024-01-25'),
        },
        {
            artistId: 34,
            title: 'Brutal Assault',
            releaseDate: new Date('2022-08-19'),
            coverUrl: 'https://picsum.photos/400x400?random=47',
            popularity: 68,
            createdAt: new Date('2022-08-19'),
        },
        // Artist 35 albums
        {
            artistId: 35,
            title: 'Speed Metal Racing',
            releaseDate: new Date('2023-12-20'),
            coverUrl: null,
            popularity: 74,
            createdAt: new Date('2023-12-20'),
        },
        // Artist 36 albums
        {
            artistId: 36,
            title: 'Power Metal Glory',
            releaseDate: new Date('2024-03-12'),
            coverUrl: 'https://picsum.photos/400x400?random=48',
            popularity: 86,
            createdAt: new Date('2024-03-12'),
        },
        {
            artistId: 36,
            title: 'Fantasy Realms',
            releaseDate: new Date('2022-10-25'),
            coverUrl: 'https://picsum.photos/400x400?random=49',
            popularity: 79,
            createdAt: new Date('2022-10-25'),
        },
        // Artist 37 albums
        {
            artistId: 37,
            title: 'Thrash Attack',
            releaseDate: new Date('2023-09-05'),
            coverUrl: 'https://picsum.photos/400x400?random=50',
            popularity: 77,
            createdAt: new Date('2023-09-05'),
        },
        // Artist 38 albums
        {
            artistId: 38,
            title: 'Gothic Symphonies',
            releaseDate: new Date('2024-04-18'),
            coverUrl: 'https://picsum.photos/400x400?random=51',
            popularity: 90,
            createdAt: new Date('2024-04-18'),
        },
        {
            artistId: 38,
            title: 'Dark Romance',
            releaseDate: new Date('2023-02-14'),
            coverUrl: 'https://picsum.photos/400x400?random=52',
            popularity: 82,
            createdAt: new Date('2023-02-14'),
        },
        // Artist 39 albums
        {
            artistId: 39,
            title: 'Industrial Revolution',
            releaseDate: new Date('2023-11-08'),
            coverUrl: null,
            popularity: 71,
            createdAt: new Date('2023-11-08'),
        },
        // Artist 40 albums
        {
            artistId: 40,
            title: 'Post Rock Landscapes',
            releaseDate: new Date('2024-01-03'),
            coverUrl: 'https://picsum.photos/400x400?random=53',
            popularity: 85,
            createdAt: new Date('2024-01-03'),
        },
        {
            artistId: 40,
            title: 'Instrumental Journeys',
            releaseDate: new Date('2022-07-11'),
            coverUrl: 'https://picsum.photos/400x400?random=54',
            popularity: 73,
            createdAt: new Date('2022-07-11'),
        },
        // Artist 41 albums
        {
            artistId: 41,
            title: 'Math Rock Equations',
            releaseDate: new Date('2023-08-16'),
            coverUrl: 'https://picsum.photos/400x400?random=55',
            popularity: 68,
            createdAt: new Date('2023-08-16'),
        },
        // Artist 42 albums
        {
            artistId: 42,
            title: 'Shoegaze Dreams',
            releaseDate: new Date('2024-02-28'),
            coverUrl: 'https://picsum.photos/400x400?random=56',
            popularity: 79,
            createdAt: new Date('2024-02-28'),
        },
        {
            artistId: 42,
            title: 'Wall of Sound',
            releaseDate: new Date('2022-11-17'),
            coverUrl: null,
            popularity: 66,
            createdAt: new Date('2022-11-17'),
        },
        // Artist 43 albums
        {
            artistId: 43,
            title: 'Noise Experiments',
            releaseDate: new Date('2023-06-08'),
            coverUrl: 'https://picsum.photos/400x400?random=57',
            popularity: 62,
            createdAt: new Date('2023-06-08'),
        },
        // Artist 44 albums
        {
            artistId: 44,
            title: 'Drone Meditations',
            releaseDate: new Date('2024-03-30'),
            coverUrl: 'https://picsum.photos/400x400?random=58',
            popularity: 67,
            createdAt: new Date('2024-03-30'),
        },
        {
            artistId: 44,
            title: 'Minimalist Compositions',
            releaseDate: new Date('2023-01-19'),
            coverUrl: 'https://picsum.photos/400x400?random=59',
            popularity: 61,
            createdAt: new Date('2023-01-19'),
        },
        // Artist 45 albums
        {
            artistId: 45,
            title: 'Darkwave Shadows',
            releaseDate: new Date('2023-10-27'),
            coverUrl: 'https://picsum.photos/400x400?random=60',
            popularity: 75,
            createdAt: new Date('2023-10-27'),
        },
        // Artist 46 albums
        {
            artistId: 46,
            title: 'Synthpop Revival',
            releaseDate: new Date('2024-04-05'),
            coverUrl: 'https://picsum.photos/400x400?random=61',
            popularity: 88,
            createdAt: new Date('2024-04-05'),
        },
        {
            artistId: 46,
            title: '80s Nostalgia',
            releaseDate: new Date('2023-03-11'),
            coverUrl: null,
            popularity: 81,
            createdAt: new Date('2023-03-11'),
        },
        // Artist 47 albums
        {
            artistId: 47,
            title: 'Chillwave Sunset',
            releaseDate: new Date('2023-07-29'),
            coverUrl: 'https://picsum.photos/400x400?random=62',
            popularity: 76,
            createdAt: new Date('2023-07-29'),
        },
        // Artist 48 albums
        {
            artistId: 48,
            title: 'Vaporwave Aesthetics',
            releaseDate: new Date('2024-01-12'),
            coverUrl: 'https://picsum.photos/400x400?random=63',
            popularity: 72,
            createdAt: new Date('2024-01-12'),
        },
        {
            artistId: 48,
            title: 'Digital Dreams',
            releaseDate: new Date('2022-05-26'),
            coverUrl: 'https://picsum.photos/400x400?random=64',
            popularity: 64,
            createdAt: new Date('2022-05-26'),
        },
        // Artist 49 albums
        {
            artistId: 49,
            title: 'Future Bass Explorations',
            releaseDate: new Date('2024-02-16'),
            coverUrl: 'https://picsum.photos/400x400?random=65',
            popularity: 83,
            createdAt: new Date('2024-02-16'),
        },
        // Artist 50 albums
        {
            artistId: 50,
            title: 'Trap House Sessions',
            releaseDate: new Date('2024-04-22'),
            coverUrl: 'https://picsum.photos/400x400?random=66',
            popularity: 94,
            createdAt: new Date('2024-04-22'),
        },
        {
            artistId: 50,
            title: 'Street Bangers EP',
            releaseDate: new Date('2023-12-01'),
            coverUrl: null,
            popularity: 87,
            createdAt: new Date('2023-12-01'),
        },
        {
            artistId: 50,
            title: 'Club Anthems',
            releaseDate: new Date('2023-06-15'),
            coverUrl: 'https://picsum.photos/400x400?random=67',
            popularity: 85,
            createdAt: new Date('2023-06-15'),
        },
        // Additional albums for some artists
        {
            artistId: 1,
            title: 'Acoustic Sessions EP',
            releaseDate: new Date('2022-09-20'),
            coverUrl: null,
            popularity: 78,
            createdAt: new Date('2022-09-20'),
        },
        {
            artistId: 3,
            title: 'Unplugged Live',
            releaseDate: new Date('2023-04-18'),
            coverUrl: 'https://picsum.photos/400x400?random=68',
            popularity: 82,
            createdAt: new Date('2023-04-18'),
        },
        {
            artistId: 5,
            title: 'Nashville Nights',
            releaseDate: new Date('2024-04-30'),
            coverUrl: 'https://picsum.photos/400x400?random=69',
            popularity: 91,
            createdAt: new Date('2024-04-30'),
        },
        {
            artistId: 6,
            title: 'Smooth Saxophone',
            releaseDate: new Date('2022-12-23'),
            coverUrl: 'https://picsum.photos/400x400?random=70',
            popularity: 76,
            createdAt: new Date('2022-12-23'),
        },
        {
            artistId: 9,
            title: 'Bedroom Pop Dreams',
            releaseDate: new Date('2024-03-05'),
            coverUrl: null,
            popularity: 80,
            createdAt: new Date('2024-03-05'),
        },
        {
            artistId: 12,
            title: 'Island Vibes',
            releaseDate: new Date('2023-05-12'),
            coverUrl: 'https://picsum.photos/400x400?random=71',
            popularity: 79,
            createdAt: new Date('2023-05-12'),
        },
        {
            artistId: 15,
            title: 'Groove Machine',
            releaseDate: new Date('2024-01-05'),
            coverUrl: 'https://picsum.photos/400x400?random=72',
            popularity: 85,
            createdAt: new Date('2024-01-05'),
        },
        {
            artistId: 17,
            title: 'Cultural Fusion',
            releaseDate: new Date('2022-08-08'),
            coverUrl: 'https://picsum.photos/400x400?random=73',
            popularity: 67,
            createdAt: new Date('2022-08-08'),
        },
        {
            artistId: 20,
            title: 'Salsa Rhythms',
            releaseDate: new Date('2023-02-28'),
            coverUrl: 'https://picsum.photos/400x400?random=74',
            popularity: 83,
            createdAt: new Date('2023-02-28'),
        },
        {
            artistId: 21,
            title: 'Highland Echoes',
            releaseDate: new Date('2024-04-14'),
            coverUrl: 'https://picsum.photos/400x400?random=75',
            popularity: 77,
            createdAt: new Date('2024-04-14'),
        },
        {
            artistId: 24,
            title: 'Seattle Sound Revival',
            releaseDate: new Date('2022-11-30'),
            coverUrl: null,
            popularity: 71,
            createdAt: new Date('2022-11-30'),
        },
        {
            artistId: 26,
            title: 'Heartbreak Chronicles',
            releaseDate: new Date('2023-12-14'),
            coverUrl: 'https://picsum.photos/400x400?random=76',
            popularity: 73,
            createdAt: new Date('2023-12-14'),
        },
        {
            artistId: 28,
            title: 'Lo-Fi Garage Sessions',
            releaseDate: new Date('2024-02-08'),
            coverUrl: 'https://picsum.photos/400x400?random=77',
            popularity: 68,
            createdAt: new Date('2024-02-08'),
        },
        {
            artistId: 30,
            title: 'Synth Pop Classics',
            releaseDate: new Date('2022-10-07'),
            coverUrl: 'https://picsum.photos/400x400?random=78',
            popularity: 74,
            createdAt: new Date('2022-10-07'),
        },
        {
            artistId: 33,
            title: 'Nordic Darkness',
            releaseDate: new Date('2024-01-28'),
            coverUrl: 'https://picsum.photos/400x400?random=79',
            popularity: 72,
            createdAt: new Date('2024-01-28'),
        },
        {
            artistId: 35,
            title: 'Lightning Fast',
            releaseDate: new Date('2022-07-03'),
            coverUrl: null,
            popularity: 66,
            createdAt: new Date('2022-07-03'),
        },
        {
            artistId: 37,
            title: 'Bay Area Thrash',
            releaseDate: new Date('2024-03-18'),
            coverUrl: 'https://picsum.photos/400x400?random=80',
            popularity: 81,
            createdAt: new Date('2024-03-18'),
        },
        {
            artistId: 39,
            title: 'Machine Rhythms',
            releaseDate: new Date('2023-08-22'),
            coverUrl: 'https://picsum.photos/400x400?random=81',
            popularity: 69,
            createdAt: new Date('2023-08-22'),
        },
        {
            artistId: 41,
            title: 'Complex Equations EP',
            releaseDate: new Date('2024-04-26'),
            coverUrl: 'https://picsum.photos/400x400?random=82',
            popularity: 65,
            createdAt: new Date('2024-04-26'),
        },
        {
            artistId: 43,
            title: 'Static Frequencies',
            releaseDate: new Date('2022-12-05'),
            coverUrl: 'https://picsum.photos/400x400?random=83',
            popularity: 58,
            createdAt: new Date('2022-12-05'),
        },
        {
            artistId: 45,
            title: 'Neon Nights',
            releaseDate: new Date('2024-02-12'),
            coverUrl: null,
            popularity: 78,
            createdAt: new Date('2024-02-12'),
        },
        {
            artistId: 47,
            title: 'Summer Vibes',
            releaseDate: new Date('2023-06-20'),
            coverUrl: 'https://picsum.photos/400x400?random=84',
            popularity: 80,
            createdAt: new Date('2023-06-20'),
        },
        {
            artistId: 49,
            title: 'Bass Adventures',
            releaseDate: new Date('2022-09-15'),
            coverUrl: 'https://picsum.photos/400x400?random=85',
            popularity: 75,
            createdAt: new Date('2022-09-15'),
        },
        // Additional random albums to reach 120
        {
            artistId: 2,
            title: 'Retro Synthwave',
            releaseDate: new Date('2021-10-10'),
            coverUrl: 'https://picsum.photos/400x400?random=86',
            popularity: 60,
            createdAt: new Date('2021-10-10'),
        },
        {
            artistId: 4,
            title: 'Dubstep Evolution',
            releaseDate: new Date('2024-04-01'),
            coverUrl: 'https://picsum.photos/400x400?random=87',
            popularity: 89,
            createdAt: new Date('2024-04-01'),
        },
        {
            artistId: 7,
            title: 'Metal Compilation',
            releaseDate: new Date('2021-05-22'),
            coverUrl: null,
            popularity: 70,
            createdAt: new Date('2021-05-22'),
        },
        {
            artistId: 11,
            title: 'Rebellion EP',
            releaseDate: new Date('2024-03-28'),
            coverUrl: 'https://picsum.photos/400x400?random=88',
            popularity: 74,
            createdAt: new Date('2024-03-28'),
        },
        {
            artistId: 13,
            title: 'Acoustic Stories',
            releaseDate: new Date('2021-08-12'),
            coverUrl: 'https://picsum.photos/400x400?random=89',
            popularity: 63,
            createdAt: new Date('2021-08-12'),
        },
        {
            artistId: 16,
            title: 'Sunday Service',
            releaseDate: new Date('2022-03-15'),
            coverUrl: 'https://picsum.photos/400x400?random=90',
            popularity: 72,
            createdAt: new Date('2022-03-15'),
        },
        {
            artistId: 18,
            title: 'Art Rock Experiments',
            releaseDate: new Date('2021-12-01'),
            coverUrl: null,
            popularity: 61,
            createdAt: new Date('2021-12-01'),
        },
        {
            artistId: 22,
            title: 'Midnight Jazz',
            releaseDate: new Date('2024-01-20'),
            coverUrl: 'https://picsum.photos/400x400?random=91',
            popularity: 84,
            createdAt: new Date('2024-01-20'),
        },
        {
            artistId: 25,
            title: 'Flex Tape Deluxe',
            releaseDate: new Date('2022-11-11'),
            coverUrl: 'https://picsum.photos/400x400?random=92',
            popularity: 81,
            createdAt: new Date('2022-11-11'),
        },
        {
            artistId: 29,
            title: 'Kaleidoscope Visions',
            releaseDate: new Date('2021-07-04'),
            coverUrl: 'https://picsum.photos/400x400?random=93',
            popularity: 65,
            createdAt: new Date('2021-07-04'),
        },
        {
            artistId: 32,
            title: 'Sludge Metal EP',
            releaseDate: new Date('2024-02-25'),
            coverUrl: 'https://picsum.photos/400x400?random=94',
            popularity: 67,
            createdAt: new Date('2024-02-25'),
        },
        {
            artistId: 34,
            title: 'Gore Fest Live',
            releaseDate: new Date('2021-06-18'),
            coverUrl: null,
            popularity: 59,
            createdAt: new Date('2021-06-18'),
        },
        {
            artistId: 36,
            title: 'Dragon Tales',
            releaseDate: new Date('2021-04-30'),
            coverUrl: 'https://picsum.photos/400x400?random=95',
            popularity: 73,
            createdAt: new Date('2021-04-30'),
        },
        {
            artistId: 38,
            title: 'Cathedral Echoes',
            releaseDate: new Date('2021-11-25'),
            coverUrl: 'https://picsum.photos/400x400?random=96',
            popularity: 76,
            createdAt: new Date('2021-11-25'),
        },
        {
            artistId: 40,
            title: 'Cinematic Scores',
            releaseDate: new Date('2023-04-08'),
            coverUrl: 'https://picsum.photos/400x400?random=97',
            popularity: 79,
            createdAt: new Date('2023-04-08'),
        },
        {
            artistId: 42,
            title: 'Reverb Waves',
            releaseDate: new Date('2021-09-12'),
            coverUrl: 'https://picsum.photos/400x400?random=98',
            popularity: 62,
            createdAt: new Date('2021-09-12'),
        },
        {
            artistId: 44,
            title: 'Subliminal Frequencies',
            releaseDate: new Date('2022-01-07'),
            coverUrl: null,
            popularity: 56,
            createdAt: new Date('2022-01-07'),
        },
        {
            artistId: 46,
            title: 'Neon Dreams',
            releaseDate: new Date('2021-10-22'),
            coverUrl: 'https://picsum.photos/400x400?random=99',
            popularity: 74,
            createdAt: new Date('2021-10-22'),
        },
        {
            artistId: 48,
            title: 'Mall Music Nostalgia',
            releaseDate: new Date('2023-09-18'),
            coverUrl: 'https://picsum.photos/400x400?random=100',
            popularity: 68,
            createdAt: new Date('2023-09-18'),
        },
        {
            artistId: 8,
            title: 'Freestyle Sessions',
            releaseDate: new Date('2022-02-14'),
            coverUrl: 'https://picsum.photos/400x400?random=101',
            popularity: 71,
            createdAt: new Date('2022-02-14'),
        },
        {
            artistId: 10,
            title: 'Chamber Music Collection',
            releaseDate: new Date('2021-03-19'),
            coverUrl: 'https://picsum.photos/400x400?random=102',
            popularity: 77,
            createdAt: new Date('2021-03-19'),
        },
        {
            artistId: 14,
            title: 'Mississippi Blues',
            releaseDate: new Date('2023-05-05'),
            coverUrl: null,
            popularity: 76,
            createdAt: new Date('2023-05-05'),
        },
        {
            artistId: 19,
            title: 'Meditation Sounds',
            releaseDate: new Date('2021-12-25'),
            coverUrl: 'https://picsum.photos/400x400?random=103',
            popularity: 69,
            createdAt: new Date('2021-12-25'),
        },
        {
            artistId: 23,
            title: 'Time Signatures',
            releaseDate: new Date('2024-04-10'),
            coverUrl: 'https://picsum.photos/400x400?random=104',
            popularity: 78,
            createdAt: new Date('2024-04-10'),
        },
        {
            artistId: 27,
            title: 'Skanking All Night',
            releaseDate: new Date('2021-05-14'),
            coverUrl: 'https://picsum.photos/400x400?random=105',
            popularity: 64,
            createdAt: new Date('2021-05-14'),
        },
        {
            artistId: 31,
            title: 'Mosh Pit Mayhem',
            releaseDate: new Date('2023-03-03'),
            coverUrl: 'https://picsum.photos/400x400?random=106',
            popularity: 70,
            createdAt: new Date('2023-03-03'),
        },
        {
            artistId: 1,
            title: 'B-Sides & Rarities',
            releaseDate: new Date('2021-01-15'),
            coverUrl: null,
            popularity: 55,
            createdAt: new Date('2021-01-15'),
        },
        {
            artistId: 3,
            title: 'Covers Album',
            releaseDate: new Date('2022-06-25'),
            coverUrl: 'https://picsum.photos/400x400?random=107',
            popularity: 71,
            createdAt: new Date('2022-06-25'),
        },
        {
            artistId: 6,
            title: 'Jazz Standards',
            releaseDate: new Date('2021-08-30'),
            coverUrl: 'https://picsum.photos/400x400?random=108',
            popularity: 80,
            createdAt: new Date('2021-08-30'),
        },
        {
            artistId: 9,
            title: 'DIY Recordings',
            releaseDate: new Date('2022-04-20'),
            coverUrl: 'https://picsum.photos/400x400?random=109',
            popularity: 66,
            createdAt: new Date('2022-04-20'),
        },
        {
            artistId: 12,
            title: 'Dub Versions',
            releaseDate: new Date('2021-11-11'),
            coverUrl: null,
            popularity: 68,
            createdAt: new Date('2021-11-11'),
        },
        {
            artistId: 15,
            title: 'Extended Jams',
            releaseDate: new Date('2022-09-09'),
            coverUrl: 'https://picsum.photos/400x400?random=110',
            popularity: 73,
            createdAt: new Date('2022-09-09'),
        },
        {
            artistId: 17,
            title: 'Global Rhythms',
            releaseDate: new Date('2024-03-01'),
            coverUrl: 'https://picsum.photos/400x400?random=111',
            popularity: 75,
            createdAt: new Date('2024-03-01'),
        },
        {
            artistId: 20,
            title: 'Bachata Nights',
            releaseDate: new Date('2021-07-21'),
            coverUrl: 'https://picsum.photos/400x400?random=112',
            popularity: 78,
            createdAt: new Date('2021-07-21'),
        },
    ];

    await db.insert(albums).values(sampleAlbums);
    
    console.log('✅ Albums seeder completed successfully - 120 albums created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});
