import { db } from '@/db';
import { artists } from '@/db/schema';

// Generate URL-friendly slug from name
function generateSlug(name: string): string {
    return name
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .replace(/\s+/g, '-')
        .replace(/-+/g, '-')
        .trim();
}

async function main() {
    const sampleArtists = [
        {
            name: 'Luna Rivers',
            slug: generateSlug('Luna Rivers'),
            bio: 'An indie-folk singer-songwriter known for her ethereal vocals and introspective lyrics. Luna combines acoustic elements with electronic textures to create a unique sonic landscape that has captivated audiences worldwide.',
            imageUrl: 'https://picsum.photos/300x300?random=1',
            bannerUrl: 'https://picsum.photos/800x400?random=1',
            popularity: 78,
            createdAt: new Date('2022-03-15'),
        },
        {
            name: 'The Midnight Echoes',
            slug: generateSlug('The Midnight Echoes'),
            bio: 'A four-piece alternative rock band from Seattle, bringing raw energy and melodic hooks to the modern rock scene. Their latest album explores themes of urban isolation and digital age anxiety.',
            imageUrl: 'https://picsum.photos/300x300?random=2',
            bannerUrl: 'https://picsum.photos/800x400?random=2',
            popularity: 82,
            createdAt: new Date('2022-05-22'),
        },
        {
            name: 'Alex Stone',
            slug: generateSlug('Alex Stone'),
            bio: null,
            imageUrl: 'https://picsum.photos/300x300?random=3',
            bannerUrl: null,
            popularity: 45,
            createdAt: new Date('2023-01-08'),
        },
        {
            name: 'Neon Collective',
            slug: generateSlug('Neon Collective'),
            bio: 'Electronic music duo specializing in synthwave and ambient soundscapes. Their live performances feature stunning visual projections that sync perfectly with their atmospheric compositions.',
            imageUrl: null,
            bannerUrl: 'https://picsum.photos/800x400?random=4',
            popularity: 65,
            createdAt: new Date('2022-09-14'),
        },
        {
            name: 'Maya Chen',
            slug: generateSlug('Maya Chen'),
            bio: 'Classical pianist and composer who bridges the gap between traditional classical music and contemporary minimalism. Her performances have graced concert halls from Carnegie to the Royal Albert.',
            imageUrl: 'https://picsum.photos/300x300?random=5',
            bannerUrl: 'https://picsum.photos/800x400?random=5',
            popularity: 72,
            createdAt: new Date('2022-07-03'),
        },
        {
            name: 'Velocity',
            slug: generateSlug('Velocity'),
            bio: null,
            imageUrl: null,
            bannerUrl: null,
            popularity: 28,
            createdAt: new Date('2024-02-18'),
        },
        {
            name: 'The Jazz Merchants',
            slug: generateSlug('The Jazz Merchants'),
            bio: 'A modern jazz quintet that blends traditional bebop with contemporary influences. Known for their improvisational skills and dynamic stage presence, they bring fresh energy to classic jazz standards.',
            imageUrl: 'https://picsum.photos/300x300?random=7',
            bannerUrl: null,
            popularity: 58,
            createdAt: new Date('2022-11-07'),
        },
        {
            name: 'Scarlett Cross',
            slug: generateSlug('Scarlett Cross'),
            bio: 'Country-pop sensation with a voice that can move from tender ballads to powerful anthems. Her storytelling captures the essence of small-town America while addressing universal themes of love and loss.',
            imageUrl: 'https://picsum.photos/300x300?random=8',
            bannerUrl: 'https://picsum.photos/800x400?random=8',
            popularity: 89,
            createdAt: new Date('2022-04-12'),
        },
        {
            name: 'Digital Horizon',
            slug: generateSlug('Digital Horizon'),
            bio: 'Progressive electronic artist pushing the boundaries of EDM with complex polyrhythms and innovative sound design. Each track is a journey through digital landscapes and cybernetic emotions.',
            imageUrl: 'https://picsum.photos/300x300?random=9',
            bannerUrl: 'https://picsum.photos/800x400?random=9',
            popularity: 73,
            createdAt: new Date('2023-03-25'),
        },
        {
            name: 'Marcus Thompson',
            slug: generateSlug('Marcus Thompson'),
            bio: null,
            imageUrl: null,
            bannerUrl: 'https://picsum.photos/800x400?random=10',
            popularity: 36,
            createdAt: new Date('2023-08-14'),
        },
        {
            name: 'Crimson Dawn',
            slug: generateSlug('Crimson Dawn'),
            bio: 'Heavy metal band known for their epic concept albums and theatrical live shows. Their music combines crushing riffs with orchestral arrangements, creating a cinematic metal experience.',
            imageUrl: 'https://picsum.photos/300x300?random=11',
            bannerUrl: 'https://picsum.photos/800x400?random=11',
            popularity: 67,
            createdAt: new Date('2022-08-30'),
        },
        {
            name: 'Phoenix Wright',
            slug: generateSlug('Phoenix Wright'),
            bio: 'R&B vocalist with a smooth, soulful voice that harkens back to the golden age while maintaining a distinctly modern edge. His music explores themes of love, resilience, and personal growth.',
            imageUrl: 'https://picsum.photos/300x300?random=12',
            bannerUrl: null,
            popularity: 54,
            createdAt: new Date('2023-05-09'),
        },
        {
            name: 'The Cosmic Drifters',
            slug: generateSlug('The Cosmic Drifters'),
            bio: null,
            imageUrl: 'https://picsum.photos/300x300?random=13',
            bannerUrl: 'https://picsum.photos/800x400?random=13',
            popularity: 41,
            createdAt: new Date('2022-12-21'),
        },
        {
            name: 'Aria Valdez',
            slug: generateSlug('Aria Valdez'),
            bio: 'Latin-pop artist blending traditional sounds with contemporary production. Her bilingual lyrics and infectious rhythms have made her a crossover sensation in both English and Spanish-speaking markets.',
            imageUrl: 'https://picsum.photos/300x300?random=14',
            bannerUrl: 'https://picsum.photos/800x400?random=14',
            popularity: 85,
            createdAt: new Date('2022-06-16'),
        },
        {
            name: 'Blackwater Blues',
            slug: generateSlug('Blackwater Blues'),
            bio: 'Three-piece blues rock band keeping the spirit of traditional blues alive with modern attitude. Their gritty performances and authentic sound have earned them a devoted following across blues festivals.',
            imageUrl: null,
            bannerUrl: 'https://picsum.photos/800x400?random=15',
            popularity: 52,
            createdAt: new Date('2023-01-29'),
        },
        {
            name: 'Echo Valley',
            slug: generateSlug('Echo Valley'),
            bio: null,
            imageUrl: 'https://picsum.photos/300x300?random=16',
            bannerUrl: null,
            popularity: 33,
            createdAt: new Date('2023-09-07'),
        },
        {
            name: 'Zara Moon',
            slug: generateSlug('Zara Moon'),
            bio: 'Experimental pop artist who creates dreamy, atmospheric tracks that blend organic instruments with digital manipulation. Her music videos are visual art pieces that complement her ethereal sound.',
            imageUrl: 'https://picsum.photos/300x300?random=17',
            bannerUrl: 'https://picsum.photos/800x400?random=17',
            popularity: 62,
            createdAt: new Date('2022-10-11'),
        },
        {
            name: 'Thunder Road',
            slug: generateSlug('Thunder Road'),
            bio: 'Classic rock revival band bringing the energy and power of 70s arena rock to modern audiences. Their guitar-driven anthems and explosive live shows create an unforgettable rock and roll experience.',
            imageUrl: 'https://picsum.photos/300x300?random=18',
            bannerUrl: 'https://picsum.photos/800x400?random=18',
            popularity: 76,
            createdAt: new Date('2022-02-28'),
        },
        {
            name: 'Kai Winters',
            slug: generateSlug('Kai Winters'),
            bio: null,
            imageUrl: null,
            bannerUrl: null,
            popularity: 19,
            createdAt: new Date('2024-01-05'),
        },
        {
            name: 'Velvet Underground Revival',
            slug: generateSlug('Velvet Underground Revival'),
            bio: 'Indie rock collective paying homage to the experimental spirit of their namesake while forging their own path. Their music explores the darker corners of human experience with beauty and grace.',
            imageUrl: 'https://picsum.photos/300x300?random=20',
            bannerUrl: null,
            popularity: 48,
            createdAt: new Date('2023-04-17'),
        },
        {
            name: 'Sage Collins',
            slug: generateSlug('Sage Collins'),
            bio: 'Folk singer-songwriter with a voice like honey and lyrics that cut straight to the heart. Her acoustic performances create intimate moments that feel like conversations with an old friend.',
            imageUrl: 'https://picsum.photos/300x300?random=21',
            bannerUrl: 'https://picsum.photos/800x400?random=21',
            popularity: 69,
            createdAt: new Date('2022-12-03'),
        },
        {
            name: 'Neon Knights',
            slug: generateSlug('Neon Knights'),
            bio: null,
            imageUrl: 'https://picsum.photos/300x300?random=22',
            bannerUrl: 'https://picsum.photos/800x400?random=22',
            popularity: 55,
            createdAt: new Date('2023-07-22'),
        },
        {
            name: 'Isabella Rodriguez',
            slug: generateSlug('Isabella Rodriguez'),
            bio: 'Classical crossover violinist who seamlessly blends traditional techniques with contemporary genres. Her performances span from concert halls to rock festivals, always leaving audiences mesmerized.',
            imageUrl: 'https://picsum.photos/300x300?random=23',
            bannerUrl: 'https://picsum.photos/800x400?random=23',
            popularity: 71,
            createdAt: new Date('2022-05-08'),
        },
        {
            name: 'The Wanderers',
            slug: generateSlug('The Wanderers'),
            bio: 'Americana band capturing the spirit of the open road with heartfelt songs about love, loss, and the American dream. Their harmonies and storytelling transport listeners to dusty highways and neon-lit diners.',
            imageUrl: null,
            bannerUrl: 'https://picsum.photos/800x400?random=24',
            popularity: 59,
            createdAt: new Date('2023-02-14'),
        },
        {
            name: 'Titanium',
            slug: generateSlug('Titanium'),
            bio: null,
            imageUrl: 'https://picsum.photos/300x300?random=25',
            bannerUrl: null,
            popularity: 24,
            createdAt: new Date('2024-03-12'),
        },
        {
            name: 'Nova Sterling',
            slug: generateSlug('Nova Sterling'),
            bio: 'Synthpop artist creating retro-futuristic soundscapes that feel both nostalgic and forward-thinking. Her music combines 80s aesthetics with modern production values for a truly unique experience.',
            imageUrl: 'https://picsum.photos/300x300?random=26',
            bannerUrl: 'https://picsum.photos/800x400?random=26',
            popularity: 64,
            createdAt: new Date('2022-09-05'),
        },
        {
            name: 'The Soul Collective',
            slug: generateSlug('The Soul Collective'),
            bio: 'Seven-piece soul and funk band bringing classic Motown energy to contemporary audiences. Their horn section and rhythm section create an infectious groove that gets everyone dancing.',
            imageUrl: 'https://picsum.photos/300x300?random=27',
            bannerUrl: 'https://picsum.photos/800x400?random=27',
            popularity: 77,
            createdAt: new Date('2022-07-19'),
        },
        {
            name: 'River Hayes',
            slug: generateSlug('River Hayes'),
            bio: null,
            imageUrl: null,
            bannerUrl: 'https://picsum.photos/800x400?random=28',
            popularity: 31,
            createdAt: new Date('2023-11-26'),
        },
        {
            name: 'Electric Shadows',
            slug: generateSlug('Electric Shadows'),
            bio: 'Dark synthwave duo creating haunting electronic compositions that blur the line between music and sound art. Their atmospheric tracks are perfect soundtracks for midnight drives through neon cities.',
            imageUrl: 'https://picsum.photos/300x300?random=29',
            bannerUrl: 'https://picsum.photos/800x400?random=29',
            popularity: 56,
            createdAt: new Date('2023-06-01'),
        },
        {
            name: 'Madison Park',
            slug: generateSlug('Madison Park'),
            bio: 'Singer-songwriter with a gift for melody and an ear for production that makes every song feel like a perfect pop gem. Her music explores the complexities of modern relationships with wit and vulnerability.',
            imageUrl: 'https://picsum.photos/300x300?random=30',
            bannerUrl: null,
            popularity: 83,
            createdAt: new Date('2022-04-26'),
        },
        {
            name: 'The Rust Belt',
            slug: generateSlug('The Rust Belt'),
            bio: null,
            imageUrl: 'https://picsum.photos/300x300?random=31',
            bannerUrl: 'https://picsum.photos/800x400?random=31',
            popularity: 42,
            createdAt: new Date('2023-08-08'),
        },
        {
            name: 'Jasmine Foster',
            slug: generateSlug('Jasmine Foster'),
            bio: 'Neo-soul vocalist with influences ranging from Erykah Badu to D\'Angelo. Her rich, textured voice and innovative arrangements push R&B in exciting new directions while honoring its roots.',
            imageUrl: 'https://picsum.photos/300x300?random=32',
            bannerUrl: 'https://picsum.photos/800x400?random=32',
            popularity: 68,
            createdAt: new Date('2022-11-14'),
        },
        {
            name: 'Stardust Highway',
            slug: generateSlug('Stardust Highway'),
            bio: 'Progressive rock band creating epic, conceptual albums that take listeners on journeys through space and time. Their technical prowess and storytelling ability set them apart in the prog rock revival.',
            imageUrl: null,
            bannerUrl: 'https://picsum.photos/800x400?random=33',
            popularity: 61,
            createdAt: new Date('2022-08-17'),
        },
        {
            name: 'Cole Anderson',
            slug: generateSlug('Cole Anderson'),
            bio: null,
            imageUrl: 'https://picsum.photos/300x300?random=34',
            bannerUrl: null,
            popularity: 27,
            createdAt: new Date('2024-01-23'),
        },
        {
            name: 'Nyx',
            slug: generateSlug('Nyx'),
            bio: 'Experimental hip-hop artist pushing the boundaries of the genre with unconventional beats and introspective lyrics. Her music tackles social issues while maintaining an otherworldly, artistic edge.',
            imageUrl: 'https://picsum.photos/300x300?random=35',
            bannerUrl: 'https://picsum.photos/800x400?random=35',
            popularity: 74,
            createdAt: new Date('2023-03-07'),
        },
        {
            name: 'The Harbor Lights',
            slug: generateSlug('The Harbor Lights'),
            bio: 'Indie folk quartet with beautiful four-part harmonies and intricate acoustic arrangements. Their songs capture the melancholy and beauty of coastal life with poetic precision.',
            imageUrl: 'https://picsum.photos/300x300?random=36',
            bannerUrl: 'https://picsum.photos/800x400?random=36',
            popularity: 53,
            createdAt: new Date('2022-12-09'),
        },
        {
            name: 'Phoenix Clark',
            slug: generateSlug('Phoenix Clark'),
            bio: null,
            imageUrl: null,
            bannerUrl: 'https://picsum.photos/800x400?random=37',
            popularity: 38,
            createdAt: new Date('2023-10-15'),
        },
        {
            name: 'Gravity Well',
            slug: generateSlug('Gravity Well'),
            bio: 'Post-rock instrumental band creating cinematic soundscapes that build from whispered beginnings to earth-shaking climaxes. Their music tells stories without words, painting emotions in sound.',
            imageUrl: 'https://picsum.photos/300x300?random=38',
            bannerUrl: 'https://picsum.photos/800x400?random=38',
            popularity: 47,
            createdAt: new Date('2023-05-31'),
        },
        {
            name: 'Ruby Diamond',
            slug: generateSlug('Ruby Diamond'),
            bio: 'Pop diva with a voice that can soar from intimate whispers to powerful anthems. Her glamorous aesthetic and catchy hooks have made her a favorite among pop music fans worldwide.',
            imageUrl: 'https://picsum.photos/300x300?random=39',
            bannerUrl: 'https://picsum.photos/800x400?random=39',
            popularity: 91,
            createdAt: new Date('2022-03-21'),
        },
        {
            name: 'The Night Shift',
            slug: generateSlug('The Night Shift'),
            bio: null,
            imageUrl: 'https://picsum.photos/300x300?random=40',
            bannerUrl: null,
            popularity: 35,
            createdAt: new Date('2023-12-04'),
        },
        {
            name: 'Indigo Rain',
            slug: generateSlug('Indigo Rain'),
            bio: 'Alternative rock band with a sound that bridges 90s grunge and modern indie rock. Their emotional intensity and raw energy create connections with audiences seeking authentic musical experiences.',
            imageUrl: null,
            bannerUrl: 'https://picsum.photos/800x400?random=41',
            popularity: 66,
            createdAt: new Date('2022-06-28'),
        },
        {
            name: 'Carmen Santos',
            slug: generateSlug('Carmen Santos'),
            bio: 'Flamenco-fusion guitarist blending traditional Spanish techniques with jazz, rock, and electronic elements. Her virtuosic playing and innovative compositions honor tradition while embracing the future.',
            imageUrl: 'https://picsum.photos/300x300?random=42',
            bannerUrl: 'https://picsum.photos/800x400?random=42',
            popularity: 70,
            createdAt: new Date('2022-10-02'),
        },
        {
            name: 'Midnight Oil Revival',
            slug: generateSlug('Midnight Oil Revival'),
            bio: null,
            imageUrl: 'https://picsum.photos/300x300?random=43',
            bannerUrl: 'https://picsum.photos/800x400?random=43',
            popularity: 44,
            createdAt: new Date('2023-07-13'),
        },
        {
            name: 'Storm Reid',
            slug: generateSlug('Storm Reid'),
            bio: 'Country-rock artist with a voice full of grit and songs full of heart. Her music captures the struggles and triumphs of working-class America with honesty and compassion.',
            imageUrl: 'https://picsum.photos/300x300?random=44',
            bannerUrl: null,
            popularity: 57,
            createdAt: new Date('2022-09-25'),
        },
        {
            name: 'The Frequency',
            slug: generateSlug('The Frequency'),
            bio: 'Electronic music collective exploring the intersection of technology and human emotion. Their live performances feature custom-built instruments and real-time audio manipulation.',
            imageUrl: null,
            bannerUrl: 'https://picsum.photos/800x400?random=45',
            popularity: 49,
            createdAt: new Date('2023-04-04'),
        },
        {
            name: 'Dante Cross',
            slug: generateSlug('Dante Cross'),
            bio: null,
            imageUrl: 'https://picsum.photos/300x300?random=46',
            bannerUrl: null,
            popularity: 22,
            createdAt: new Date('2024-02-07'),
        },
        {
            name: 'Silver Lake',
            slug: generateSlug('Silver Lake'),
            bio: 'Dreampop band creating lush, atmospheric music that feels like floating through clouds. Their ethereal soundscapes and haunting melodies transport listeners to otherworldly realms.',
            imageUrl: 'https://picsum.photos/300x300?random=47',
            bannerUrl: 'https://picsum.photos/800x400?random=47',
            popularity: 63,
            createdAt: new Date('2022-11-30'),
        },
        {
            name: 'Atlas Stone',
            slug: generateSlug('Atlas Stone'),
            bio: 'Hip-hop producer and MC known for intricate wordplay and innovative beats. His music addresses social issues while showcasing technical skills that have earned respect throughout the hip-hop community.',
            imageUrl: 'https://picsum.photos/300x300?random=48',
            bannerUrl: 'https://picsum.photos/800x400?random=48',
            popularity: 79,
            createdAt: new Date('2022-05-15'),
        },
        {
            name: 'The Aurora Project',
            slug: generateSlug('The Aurora Project'),
            bio: null,
            imageUrl: null,
            bannerUrl: 'https://picsum.photos/800x400?random=49',
            popularity: 39,
            createdAt: new Date('2023-09-28'),
        },
        {
            name: 'Violet Storm',
            slug: generateSlug('Violet Storm'),
            bio: 'Pop-punk princess with an attitude and anthems that speak to a generation. Her high-energy performances and relatable lyrics have made her a voice for young people navigating modern life.',
            imageUrl: 'https://picsum.photos/300x300?random=50',
            bannerUrl: 'https://picsum.photos/800x400?random=50',
            popularity: 87,
            createdAt: new Date('2022-01-18'),
        }
    ];

    await db.insert(artists).values(sampleArtists);

    console.log('✅ Artists seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});
