import { db } from '@/db';
import { trackSubmissions } from '@/db/schema';

async function main() {
    const sampleTrackSubmissions = [
        {
            userId: 'user-123',
            creatorId: 1,
            title: 'Midnight Echoes',
            artistsCsv: 'Alex Rivers',
            album: 'Digital Dreams',
            releaseDate: new Date('2024-01-15'),
            genre: 'Electronic',
            explicit: false,
            coverUrl: 'https://example.com/covers/midnight-echoes.jpg',
            sourceType: 'upload',
            originalUrl: null,
            audioUrl: 'https://cdn.musicapp.com/tracks/midnight-echoes.mp3',
            durationSec: 243,
            bitrateKbps: 320,
            state: 'live',
            rejectionReason: null,
            processingLog: JSON.stringify([
                { timestamp: '2024-01-15T10:00:00Z', state: 'submitted', note: 'Track submitted for review' },
                { timestamp: '2024-01-15T14:30:00Z', state: 'processing', note: 'Audio quality check passed' },
                { timestamp: '2024-01-15T16:45:00Z', state: 'live', note: 'Track approved and published' }
            ]),
            createdAt: new Date('2024-01-15T10:00:00Z'),
            updatedAt: new Date('2024-01-15T16:45:00Z'),
            lastUpdate: new Date('2024-01-15T16:45:00Z'),
        },
        {
            userId: 'user-123',
            creatorId: 1,
            title: 'Summer Vibes',
            artistsCsv: 'Alex Rivers, Maya Chen',
            album: 'Seasonal Moods',
            releaseDate: new Date('2024-02-01'),
            genre: 'Pop',
            explicit: false,
            coverUrl: 'https://example.com/covers/summer-vibes.jpg',
            sourceType: 'external',
            originalUrl: 'https://soundcloud.com/alexrivers/summer-vibes',
            audioUrl: 'https://cdn.musicapp.com/tracks/summer-vibes.mp3',
            durationSec: 198,
            bitrateKbps: 256,
            state: 'live',
            rejectionReason: null,
            processingLog: JSON.stringify([
                { timestamp: '2024-02-01T09:15:00Z', state: 'submitted', note: 'External track submitted' },
                { timestamp: '2024-02-01T11:20:00Z', state: 'processing', note: 'Downloading from external source' },
                { timestamp: '2024-02-01T13:10:00Z', state: 'live', note: 'Track processed and approved' }
            ]),
            createdAt: new Date('2024-02-01T09:15:00Z'),
            updatedAt: new Date('2024-02-01T13:10:00Z'),
            lastUpdate: new Date('2024-02-01T13:10:00Z'),
        },
        {
            userId: 'user-123',
            creatorId: 1,
            title: 'Broken Dreams',
            artistsCsv: 'Alex Rivers',
            album: 'Raw Emotions',
            releaseDate: new Date('2024-02-10'),
            genre: 'Alternative Rock',
            explicit: true,
            coverUrl: null,
            sourceType: 'upload',
            originalUrl: null,
            audioUrl: null,
            durationSec: 287,
            bitrateKbps: 192,
            state: 'submitted',
            rejectionReason: null,
            processingLog: JSON.stringify([
                { timestamp: '2024-02-10T15:30:00Z', state: 'submitted', note: 'Track uploaded and awaiting review' }
            ]),
            createdAt: new Date('2024-02-10T15:30:00Z'),
            updatedAt: new Date('2024-02-10T15:30:00Z'),
            lastUpdate: new Date('2024-02-10T15:30:00Z'),
        },
        {
            userId: 'user-123',
            creatorId: 1,
            title: 'City Lights',
            artistsCsv: 'Alex Rivers, The Night Collective',
            album: 'Urban Stories',
            releaseDate: new Date('2024-02-15'),
            genre: 'Hip Hop',
            explicit: false,
            coverUrl: 'https://example.com/covers/city-lights.jpg',
            sourceType: 'external',
            originalUrl: 'https://youtube.com/watch?v=citylight123',
            audioUrl: null,
            durationSec: 205,
            bitrateKbps: 320,
            state: 'submitted',
            rejectionReason: null,
            processingLog: JSON.stringify([
                { timestamp: '2024-02-15T12:00:00Z', state: 'submitted', note: 'External source track submitted for review' }
            ]),
            createdAt: new Date('2024-02-15T12:00:00Z'),
            updatedAt: new Date('2024-02-15T12:00:00Z'),
            lastUpdate: new Date('2024-02-15T12:00:00Z'),
        },
        {
            userId: 'user-123',
            creatorId: 1,
            title: 'Ocean Waves',
            artistsCsv: 'Alex Rivers',
            album: 'Nature Sounds',
            releaseDate: new Date('2024-02-20'),
            genre: 'Ambient',
            explicit: false,
            coverUrl: 'https://example.com/covers/ocean-waves.jpg',
            sourceType: 'upload',
            originalUrl: null,
            audioUrl: null,
            durationSec: 456,
            bitrateKbps: 256,
            state: 'needs_review',
            rejectionReason: null,
            processingLog: JSON.stringify([
                { timestamp: '2024-02-20T08:45:00Z', state: 'submitted', note: 'Ambient track submitted' },
                { timestamp: '2024-02-20T10:15:00Z', state: 'processing', note: 'Audio processing completed' },
                { timestamp: '2024-02-20T11:30:00Z', state: 'needs_review', note: 'Flagged for manual review - unusual duration' }
            ]),
            createdAt: new Date('2024-02-20T08:45:00Z'),
            updatedAt: new Date('2024-02-20T11:30:00Z'),
            lastUpdate: new Date('2024-02-20T11:30:00Z'),
        },
        {
            userId: 'user-123',
            creatorId: 1,
            title: 'Dance Floor',
            artistsCsv: 'Alex Rivers, DJ Pulse',
            album: 'Club Nights',
            releaseDate: new Date('2024-02-25'),
            genre: 'Dance',
            explicit: false,
            coverUrl: null,
            sourceType: 'external',
            originalUrl: 'https://soundcloud.com/djpulse/dance-floor-remix',
            audioUrl: null,
            durationSec: 321,
            bitrateKbps: 320,
            state: 'needs_review',
            rejectionReason: null,
            processingLog: JSON.stringify([
                { timestamp: '2024-02-25T14:20:00Z', state: 'submitted', note: 'Dance remix submitted' },
                { timestamp: '2024-02-25T15:45:00Z', state: 'processing', note: 'Extracting audio from external source' },
                { timestamp: '2024-02-25T17:10:00Z', state: 'needs_review', note: 'Potential copyright issue detected' }
            ]),
            createdAt: new Date('2024-02-25T14:20:00Z'),
            updatedAt: new Date('2024-02-25T17:10:00Z'),
            lastUpdate: new Date('2024-02-25T17:10:00Z'),
        },
        {
            userId: 'user-123',
            creatorId: 1,
            title: 'Explicit Lyrics Track',
            artistsCsv: 'Alex Rivers',
            album: 'Uncensored',
            releaseDate: new Date('2024-03-01'),
            genre: 'Rap',
            explicit: true,
            coverUrl: 'https://example.com/covers/explicit-track.jpg',
            sourceType: 'upload',
            originalUrl: null,
            audioUrl: null,
            durationSec: 178,
            bitrateKbps: 256,
            state: 'rejected',
            rejectionReason: 'Content violates community guidelines - excessive profanity and inappropriate themes',
            processingLog: JSON.stringify([
                { timestamp: '2024-03-01T16:00:00Z', state: 'submitted', note: 'Explicit content track submitted' },
                { timestamp: '2024-03-01T17:30:00Z', state: 'processing', note: 'Content moderation in progress' },
                { timestamp: '2024-03-01T18:45:00Z', state: 'rejected', note: 'Rejected due to policy violations' }
            ]),
            createdAt: new Date('2024-03-01T16:00:00Z'),
            updatedAt: new Date('2024-03-01T18:45:00Z'),
            lastUpdate: new Date('2024-03-01T18:45:00Z'),
        },
        {
            userId: 'user-123',
            creatorId: 1,
            title: 'Instrumental Journey',
            artistsCsv: 'Alex Rivers',
            album: 'Soundscapes',
            releaseDate: new Date('2024-03-05'),
            genre: 'Instrumental',
            explicit: false,
            coverUrl: 'https://example.com/covers/instrumental-journey.jpg',
            sourceType: 'external',
            originalUrl: 'https://bandcamp.com/alexrivers/instrumental-journey',
            audioUrl: null,
            durationSec: 389,
            bitrateKbps: 320,
            state: 'processing',
            rejectionReason: null,
            processingLog: JSON.stringify([
                { timestamp: '2024-03-05T11:15:00Z', state: 'submitted', note: 'Instrumental track from Bandcamp submitted' },
                { timestamp: '2024-03-05T12:30:00Z', state: 'processing', note: 'High-quality audio extraction in progress' }
            ]),
            createdAt: new Date('2024-03-05T11:15:00Z'),
            updatedAt: new Date('2024-03-05T12:30:00Z'),
            lastUpdate: new Date('2024-03-05T12:30:00Z'),
        }
    ];

    await db.insert(trackSubmissions).values(sampleTrackSubmissions);
    
    console.log('✅ Track submissions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});
